### ISSUE TITLE
Copyright notice

### ISSUE THREAD

**Issue by FMCorz** [JotaDF/moodle-availability_game#3]
Hi,

It appears that some portions of this plugin have been copied from https://github.com/FMCorz/moodle-availability_xp

(The readme is phrased identically, language strings IDs are the same, and some other things appear very similar)

While we have no problem with the fact that Open Source code is used to create more Open Source code, it is not right to remove the copyright statement of the original authors. This is not limited to me, but also to contributors such as Jan Dageförde.

> If you have copied code from other programs covered by the same license, copy their copyright notices too. Put all the copyright notices for a file together, right near the top of the file.
> https://www.gnu.org/licenses/gpl-howto.en.html

Thank you!

**Comment by JotaDF** [comment]
Hi Frédéric,
There was no code copying, if you look at both plugins they reference
another gamification plugin, where they work with game levels. That's why
there are similarities. But the code of that plugin is quite different from
my plugin.

--
Thanks,

José Wilson


Em seg., 2 de ago. de 2021 às 04:01, Frédéric Massart <
***@***.***> escreveu:

**Comment by FMCorz** [comment]
Hi @JotaDF,

The code is different, but there are files that are almost identical as per the examples I gave above. Now it may be a coincidence that two plugins with related functionality use identical language string identifiers, README, file headings, etc. but allow me to be sceptical.

I'll close this issue as all I wanted was to get share this.

Thank you!
